name: markdown

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - .github/workflows/markdown.yaml
  pull_request:
    paths:
      - '**.md'
      - .github/workflows/markdown.yaml
  repository_dispatch:
    types:
      - markdown

jobs:
  lint:
    if: "!(github.event.client_payload.scope == 'job' && !contains(github.event.client_payload.jobs, 'lint'))"
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          config_file: markdownlint.yml
          files: .
          ignore_files: cue.mode/*
